language: php

php:
  - 7.2

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpcs --standard=PSR2 ./

cache:
  directories:
    - vendor/

notifications:
  email: false
