# Development services extension for docker-compose
# Additional Services:
# - phpMyAdmin: http://www.example.com:8002 (Use host: restarters_db, user: root/s3cr3t)
# - Mailhog: http://localhost:8025 (SMTP server on port 1025)
#
# Development Tools:
# - phpMyAdmin: Database management interface
#   - Access at http://www.example.com:8002
#   - Use host: restarters_db, username: root, password: s3cr3t
#
# - Mailhog: Email testing tool
#   - Web interface: http://localhost:8025
#   - SMTP server: localhost:1025
#   - All emails from the application will be caught here
#

version: '3'
services:
  restarters:
    environment:
      MAIL_HOST: restarters_mailhog
      MAIL_PORT: 1025

  phpmyadmin:
    depends_on:
      - restarters_db
    image: phpmyadmin
    container_name: restarters_phpmyadmin
    restart: unless-stopped
    ports:
      - 8002:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=restarters_db
#      - PMA_USER=root
#      - PMA_PASSWORD=s3cr3t
    networks:
      - app-network
  mailhog:
    image: mailhog/mailhog
    container_name: restarters_mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - app-network