version: "3"

volumes:
  dbdata:

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    ports:
      - "8000:8181"
    volumes:
      - .:/app
    env_file: ./compose/local/env
    working_dir: /app
    command: /start.sh
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    env_file: ./compose/local/env
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    logging:
      driver: none

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - 8090:80
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: yourpassword
