# https://taskfile.dev

version: "3"

# Load environment-specific .env file
dotenv:
  - .env

env:
  UID:
    sh: |
      if command -v id >/dev/null 2>&1; then
        id -u
      else
        echo "1000"
      fi
  GID:
    sh: |
      if command -v id >/dev/null 2>&1; then
        id -g
      else
        echo "1000"
      fi

vars:
  DOCKER_CMD:
    sh: command -v docker-compose &> /dev/null && echo "docker-compose" || echo "docker compose"
  COMPOSE_PROFILES:
    map:
      all: "'*'"
      core: "core"
      debug: "debug"
      discourse: "discourse"

tasks:
  # Default task
  default:
    desc: List all tasks
    cmds:
      - task --list

  # Docker container management tasks
  docker:up-*:
    desc: Start Docker containers for a given profile (Usage - task docker:up-[core|debug|discourse|all])
    summary: |
      Start a set of Docker containers at a given time. The core services are always started with any profile.
      For just the core services, use:
      task docker:up-core

      To include phpMyAdmin and Mailhog, use:
      task docker:up-debug

      To include the Discourse set of containers, use:
      task docker:up-discourse

      If you want to start all containers, use:
      task docker:up-all

    requires: &PROFILE_REQUIRES
      vars:
        - name: PROFILE
          enum: [core, debug, discourse, all]
    
    vars: &PROFILE_VARS
      PROFILE: "{{index .MATCH 0}}"

    cmds:
      - '{{.DOCKER_CMD}} --profile {{ index .COMPOSE_PROFILES .PROFILE }} up -d'

  docker:down-*:
    desc: Stop Docker containers for a given profile (Usage - task docker:down-[core|debug|discourse|all])
    summary: |
      Stop a set of Docker containers at a given time. The core services are always stopped with any profile.
      For just the core services, use:
      task docker:down-core

      To include phpMyAdmin and Mailhog, use:
      task docker:down-debug

      To include the Discourse set of containers, use:
      task docker:down-discourse

      If you want to stop all containers, use:
      task docker:down-all

    requires: *PROFILE_REQUIRES
    
    vars: *PROFILE_VARS

    cmds:
      - '{{.DOCKER_CMD}} --profile {{ index .COMPOSE_PROFILES .PROFILE }} down'

  docker:rebuild-*:
    desc: Rebuild Docker containers for a given profile (Usage - task docker:rebuild-[core|debug|discourse|all])
    summary: |
      Rebuild a set of Docker containers at a given time. The core services are always rebuilt with any profile.
      For just the core services, use:
      task docker:rebuild-core

      To include phpMyAdmin and Mailhog, use:
      task docker:rebuild-debug

      To include the Discourse set of containers, use:
      task docker:rebuild-discourse

      To rebuild all containers, use:
      task docker:rebuild-all

    requires: *PROFILE_REQUIRES
    
    vars: *PROFILE_VARS

    cmds:
      - '{{.DOCKER_CMD}} --profile {{ index .COMPOSE_PROFILES .PROFILE }} down -v --rmi all'
      - '{{.DOCKER_CMD}} --profile {{ index .COMPOSE_PROFILES .PROFILE }} up -d'

  docker:restart-*:
    desc: Restart Docker containers for a given profile (Usage - task docker:restart-[core|debug|discourse|all])
    summary: |
      Restart a set of Docker containers at a given time. The core services are always restarted with any profile.
      For just the core services, use:
      task docker:restart-core

      To include phpMyAdmin and Mailhog, use:
      task docker:restart-debug

      To include the Discourse set of containers, use:
      task docker:restart-discourse

      To restart all containers, use:
      task docker:restart-all

    requires: *PROFILE_REQUIRES
    
    vars: *PROFILE_VARS

    cmds:
      - '{{.DOCKER_CMD}} --profile {{ index .COMPOSE_PROFILES .PROFILE }} restart'


  docker:logs:
    desc: Show the logs for the core application container.
    cmds:
      - cmd: docker logs -f restarters
        ignore_error: true


  docker:shell:
    desc: Open a shell into the core application container.
    cmds:
      - cmd: docker exec -it restarters bash
        ignore_error: true

  docker:run:bash:
    desc: Run a bash command in the core application container.
    summary: |
      Run a bash command in the core application container. To pass the arguments, use the -- flag.
      For example, to run the ls command, use:
      task docker:run:bash -- ls -la

    cmds:
      - docker exec -it restarters bash -c "{{ .CLI_ARGS }}"

  docker:run:artisan:
    desc: Run an artisan command in the core application container.
    summary: |
      Run an artisan command in the core application container. To pass the arguments, use the -- flag.
      For example, to run the migrate command, use:
      task docker:run:artisan -- migrate

    cmds:
      - docker exec -it restarters php artisan "{{ .CLI_ARGS }}"

  docker:wait-for-services-*:
    desc: Wait for Docker services to be ready and responding for a given profile (Usage - task docker:wait-for-services-[core|debug|discourse|all])
    summary: |
      Wait for Docker services to be ready by checking their health endpoints.
      This task will check that services are listening on their ports and returning
      plausible responses before proceeding, but only for the services in the specified profile.
      
      For just the core services, use:
      task docker:wait-for-services-core
      
      To include debug tools (phpMyAdmin, Mailhog), use:
      task docker:wait-for-services-debug
      
      To include Discourse services, use:
      task docker:wait-for-services-discourse
      
      To wait for all services, use:
      task docker:wait-for-services-all
      
      The task checks:
      - Core profile: MySQL database, Restarters web app
      - Debug profile: Core + phpMyAdmin, Mailhog  
      - Discourse profile: Core + Discourse, PostgreSQL, Redis, Sidekiq
      - All profile: All services
      
    requires: *PROFILE_REQUIRES
    
    vars: *PROFILE_VARS

    cmds:
      - |
        # Cross-platform sleep function
        cross_platform_sleep() {
          if command -v sleep >/dev/null 2>&1; then
            sleep "$1"
          elif command -v powershell >/dev/null 2>&1; then
            powershell -Command "Start-Sleep -Seconds $1"
          else
            # Fallback using ping (works on most systems)
            ping -n $(($1 + 1)) 127.0.0.1 >/dev/null 2>&1 || ping -c $1 127.0.0.1 >/dev/null 2>&1
          fi
        }
        
        # Generic wait function that takes: service_name, check_command, max_attempts, sleep_interval
        wait_for_service() {
          local service_name="$1"
          local check_command="$2" 
          local max_attempts="$3"
          local sleep_interval="$4"
          
          echo "Waiting for $service_name..."
          local attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if eval "$check_command" >/dev/null 2>&1; then
              echo "✓ $service_name is ready"
              return 0
            fi
            echo "  $service_name not ready, waiting... (attempt $((attempt + 1))/$max_attempts)"
            cross_platform_sleep "$sleep_interval"
            attempt=$((attempt + 1))
          done
          echo "❌ $service_name failed to start after $max_attempts attempts"
          exit 1
        }
        
        echo "Waiting for services in profile: {{.PROFILE}}"
        echo ""
        
        # Wait for core services (always needed)
        wait_for_service "MySQL database" "docker exec restarters_db mysqladmin ping -h localhost -u root -ps3cr3t --silent" 60 5
        wait_for_service "Restarters web application" "curl -f -s http://localhost:8001" 60 5
        
        # Wait for debug services (if in debug or all profile)
        {{- if or (eq .PROFILE "debug") (eq .PROFILE "all") }}
        wait_for_service "phpMyAdmin" "curl -f -s http://localhost:8002" 60 5
        wait_for_service "Mailhog" "curl -f -s http://localhost:8025" 60 5
        {{- else }}
        echo "✓ phpMyAdmin not in profile {{.PROFILE}}, skipping"
        echo "✓ Mailhog not in profile {{.PROFILE}}, skipping"
        {{- end }}
        
        # Wait for discourse services (if in discourse or all profile)
        {{- if or (eq .PROFILE "discourse") (eq .PROFILE "all") }}
        wait_for_service "PostgreSQL" "docker exec postgresql pg_isready -U postgres" 60 5
        wait_for_service "Discourse" "curl -f -s http://localhost:8003" 120 10
        {{- else }}
        echo "✓ PostgreSQL not in profile {{.PROFILE}}, skipping"
        echo "✓ Discourse not in profile {{.PROFILE}}, skipping"
        {{- end }}
      - echo "🎉 All services in profile {{.PROFILE}} are ready!"