# https://taskfile.dev

version: "3"

# Load environment-specific .env file
dotenv:
  - .env

vars:
  COMPOSE_FILES:
    map:
      all: "-f docker-compose.yml -f docker-compose.discourse.yml -f docker-compose.dev.yml"
      discourse: "-f docker-compose.yml -f docker-compose.discourse.yml"
      dev: "-f docker-compose.yml -f docker-compose.dev.yml"

tasks:
  # Default task
  default:
    desc: List all tasks
    cmds:
      - task --list

  docker:up:
    desc: Start Base Docker containers (Usage - task docker:up)
    summary: |
      Start the base stack of Docker containers.
      This includes the Restarters app and the database.
    cmds:
      - docker compose up -d

  docker:up-*:
    desc: Start Docker containers (Usage - task docker:up-[dev|discourse|all])
    summary: |
      Start a set of Docker containers at a given time. This will always start the base services.
      For example, to include PHPMyAdmin and Mailhog, use:
      task docker:up-dev

      To include the Discourse set of containers, use:
      task docker:up-discourse

      If you want to start all containers, use:
      task docker:up-all

    requires:
      vars:
        - name: STACK
          enum: [dev, discourse, all]
    
    vars:
      STACK: "{{index .MATCH 0}}"

    cmds:
      - docker compose {{ index .COMPOSE_FILES .STACK }} up -d

  
  docker:down:
    desc: Stop Base Docker containers (Usage - task docker:down)
    summary: |
      Stop the base stack of Docker containers.
      This includes the Restarters app and the database.
    cmds:
      - docker compose down

  docker:down-*:
    desc: Stop Docker containers (Usage - task docker:down-[dev|discourse|all])
    summary: |
      Stop a set of Docker containers at a given time. This will always stop the base services.
      For example, to include PHPMyAdmin and Mailhog, use:
      task docker:down-dev

      To include the Discourse set of containers, use:
      task docker:down-discourse

      If you want to stop all containers, use:
      task docker:down-all

    requires:
      vars:
        - name: STACK
          enum: [dev, discourse, all]
    
    vars:
      STACK: "{{index .MATCH 0}}"

    cmds:
      - docker compose {{ index .COMPOSE_FILES .STACK }} down


  docker:rebuild:
    desc: Rebuild Docker containers (Usage - task docker:rebuild)
    summary: |
      Rebuild the base stack of Docker containers.
      This includes the Restarters app and the database.
    cmds:
      - docker compose down -v --rmi all
      - docker compose up -d

  docker:rebuild-*:
    desc: Rebuild Docker containers (Usage - task docker:rebuild-[dev|discourse|all])
    summary: |
      Rebuild a set of Docker containers at a given time. This will always rebuild the base services.
      For example, to rebuild the development stack, use:
      task docker:rebuild-dev

      To rebuild the discourse stack, use:
      task docker:rebuild-discourse

      To rebuild all containers, use:
      task docker:rebuild-all

    requires:
      vars:
        - name: STACK
          enum: [dev, discourse, all]
    
    vars:
      STACK: "{{index .MATCH 0}}"

    cmds:
      - docker compose {{ index .COMPOSE_FILES .STACK }} down -v --rmi all
      - docker compose {{ index .COMPOSE_FILES .STACK }} up -d