update devices set category=(select idcategories from categories where name='Aircon/Dehumidifier') where iddevices=1182;
update devices set category=(select idcategories from categories where name='Aircon/Dehumidifier') where iddevices=1925;
update devices set category=(select idcategories from categories where name='Decorative or safety lights') where iddevices=5986;
update devices set category=(select idcategories from categories where name='Desktop computer') where iddevices=6732;
update devices set category=(select idcategories from categories where name='Desktop computer') where iddevices=6618;
update devices set category=(select idcategories from categories where name='DLSR / Video Camera') where iddevices=1665;
update devices set category=(select idcategories from categories where name='Hair & Beauty item') where iddevices=7459;
update devices set category=(select idcategories from categories where name='Hair & Beauty item') where iddevices=5504;
update devices set category=(select idcategories from categories where name='Hair & Beauty item') where iddevices=6151;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=7165;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=7221;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=7471;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=7763;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=7833;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=1849;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=2271;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=3451;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=4110;
update devices set category=(select idcategories from categories where name='Handheld Entertainment device') where iddevices=4113;
update devices set category=(select idcategories from categories where name='Headphones') where iddevices=4139;
update devices set category=(select idcategories from categories where name='Headphones') where iddevices=4162;
update devices set category=(select idcategories from categories where name='Headphones') where iddevices=4166;
update devices set category=(select idcategories from categories where name='Headphones') where iddevices=4169;
update devices set category=(select idcategories from categories where name='Hi-Fi integrated') where iddevices=2905;
update devices set category=(select idcategories from categories where name='Hi-Fi integrated') where iddevices=5699;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=3544;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=1600;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=1662;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=1743;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=1899;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=2238;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=2241;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=4205;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=5515;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=6452;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=6550;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=6567;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=6741;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=3858;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7089;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7331;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7335;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7448;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7463;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7475;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7673;
update devices set category=(select idcategories from categories where name='Hi-Fi separates') where iddevices=7674;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=1339;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=1882;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=2226;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=2756;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=2811;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=2992;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=3377;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=3626;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4087;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4124;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4183;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4253;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4401;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4409;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4446;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4636;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4663;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4686;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4752;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4859;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5028;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5039;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5040;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5151;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5152;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5250;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5650;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5669;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6063;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6134;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6549;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7178;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7640;
update devices set category=(select idcategories from categories where name='Lamp') where iddevices=2994;
update devices set category=(select idcategories from categories where name='Lamp') where iddevices=5281;
update devices set category=(select idcategories from categories where name='Lamp') where iddevices=7340;
update devices set category=(select idcategories from categories where name='Mobile') where iddevices=4171;
update devices set category=(select idcategories from categories where name='Musical instrument') where iddevices=3751;
update devices set category=(select idcategories from categories where name='Musical instrument') where iddevices=3755;
update devices set category=(select idcategories from categories where name='Musical instrument') where iddevices=3680;
update devices set category=(select idcategories from categories where name='Musical instrument') where iddevices=5557;
update devices set category=(select idcategories from categories where name='Paper shredder') where iddevices=5270;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=1845;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=3585;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=3896;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=5499;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=6538;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=1664;
update devices set category=(select idcategories from categories where name='PC Accessory') where iddevices=7454;
update devices set category=(select idcategories from categories where name='Portable radio') where iddevices=6557;
update devices set category=(select idcategories from categories where name='Portable radio') where iddevices=6619;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=2344;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=7038;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=7363;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=3928;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=3929;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=3978;
update devices set category=(select idcategories from categories where name='Power tool') where iddevices=3979;
update devices set category=(select idcategories from categories where name='Printer/scanner') where iddevices=3358;
update devices set category=(select idcategories from categories where name='Printer/scanner') where iddevices=3942;
update devices set category=(select idcategories from categories where name='Projector') where iddevices=6881;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7174;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=1133;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=1842;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=3021;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=3056;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=3337;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4600;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4613;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4614;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4671;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=4948;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5276;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5327;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5397;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=5688;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6171;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6698;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6719;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6731;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6755;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=6765;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7450;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7453;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7576;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7630;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7649;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7713;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7758;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=7962;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8092;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8099;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8100;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8116;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8126;
update devices set category=(select idcategories from categories where name='Small kitchen item') where iddevices=8132;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=1617;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=1626;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=1736;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=1841;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=1844;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=2000;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=2216;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=2340;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=3569;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=3578;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=3579;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=3582;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=3974;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=4561;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=4577;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=5021;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=5033;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=5058;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=6738;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=7705;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=7724;
update devices set category=(select idcategories from categories where name='TV and gaming-related accessories') where iddevices=7902;
